### ISSUE TITLE
Pagination is required

### ISSUE THREAD

**Issue by dipshikha-adhikari** [AnupamKhosla/reactMusic#1]
I want to add pagination so that it does not take too much space in a single page when there are many radios available. If the project is active, I would like to implement that feature.

**Comment by AnupamKhosla** [comment]
Hey mate, thanks for the suggestion. Yes, the project is still active.  

If I understand correctly, you mean, you want to reduce the number of radio channels(results) per page, so that the user doesn't have to scroll a lot? At the moment, I have set the number of results(cards) to 12, which can be changed to 3 for example quite easily here: https://github.com/AnupamKhosla/reactMusic/blob/5e1840a150963a585d5c1acbd31c192228339cd5/src/js/App.js#L69  

You can branch off and implement that. I am happy with the current height of the page though.

**Comment by dipshikha-adhikari** [comment]
I am sorry, I did not see pagination at first. It would have been better if the pagination was at the bottom. Anyway the UI looks so cool!

**Comment by AnupamKhosla** [comment]
Yeah. I kept the pagination at top because I wanted to showcase UI feature upfront to possible job recruiters.

**Comment by dipshikha-adhikari** [comment]
Your idea is good but it would have been easier for a user to navigate to next items from the bottom instead of scrolling to the top again. Anyway user and recruiter are two different things.
